### ISSUE TITLE
Standard JS Format

### ISSUE THREAD

**Issue by kooparse** [electrodejs/deprecated-generator-electrode#38]
Hi there!

What do you think about adding the [standard style guide](https://github.com/feross/standard) ?
We could do that with a simple question on the app initiation with Yeoman.

If you agree with that, I will make a PR 👍

**Comment by jchip** [comment]
It'd be a nice addition, but it would require some changes to the electrode archetypes, particularly electrode-archetype-react-app.

At the moment the eslint configs comes from archetype and the build commands there point to those configs.  I've been thinking about how to allow user eslint configs.  One way is to detect the existence of .eslintrc in CWD and CWD/test, and use those instead of the configs come with the archetype.

**Comment by kooparse** [comment]
https://github.com/electrode-io/electrode-archetype-react-app/pull/35 👍
